var getArrObj = new Object();
getArrObj.getFishInfo=function(){
    return [

        {
            name:"changeAngle"
        },
        {
            name:"moveForward"
        },
        {
            centerObj:true,
            name:"isScreenOut"
        },
        {
            centerObj:true,
            name:"deathAfter"
        }
    ]
};
getArrObj.getFishInfo02=function(){
    return [
        {
            name:"changeImgInfo"
        }
    ]
};
/*0图片信息 1创建鱼的信息 2场景信息 3鱼群的类型*/
var cjData = [
    [
        [
            "img/fish/fish1.png",
            "img/fish/fish2.png",
            "img/fish/fish3.png",
            "img/fish/fish4.png",
            "img/fish/fish5.png",
            "img/fish/fish6.png",
            "img/fish/fish7.png",
            "img/fish/fish8.png",
            "img/fish/fish9.png",
            "img/fish/fish10.png",
            "img/fish/shark1.png"
        ],
        [
        ],
        "img/Interface/e.jpg",
        []
    ],
    [
        [
            "img/fish/fish1.png",
            "img/fish/fish2.png",
            "img/fish/fish3.png",
            "img/fish/fish4.png",
            "img/fish/fish5.png",
            "img/fish/fish6.png",
            "img/fish/fish7.png",
            "img/fish/fish8.png",
            "img/fish/fish9.png",
            "img/fish/fish10.png",
            "img/fish/shark1.png"
        ],
        [


        ],
        "img/Interface/game_bg_2_hd.jpg",
        []
    ],
    [
        [
            "img/fish/fish1.png",
            "img/fish/fish2.png",
            "img/fish/fish3.png",
            "img/fish/fish4.png",
            "img/fish/fish5.png",
            "img/fish/fish6.png",
            "img/fish/fish7.png",
            "img/fish/fish8.png",
            "img/fish/fish9.png",
            "img/fish/fish10.png",
            "img/fish/shark1.png"
        ],
        [


        ],
        "img/Interface/bg1.jpg",
        []
    ],
    [
        [
            "img/fish/fish1.png",
            "img/fish/fish2.png",
            "img/fish/fish3.png",
            "img/fish/fish4.png",
            "img/fish/fish5.png",
            "img/fish/fish6.png",
            "img/fish/fish7.png",
            "img/fish/fish8.png",
            "img/fish/fish9.png",
            "img/fish/fish10.png",
            "img/fish/shark1.png"
        ],
        [


        ],
        "img/Interface/startbg.jpg",
        []
    ],
    [
        [
            "img/fish/fish1.png",
            "img/fish/fish2.png",
            "img/fish/fish3.png",
            "img/fish/fish4.png",
            "img/fish/fish5.png",
            "img/fish/fish6.png",
            "img/fish/fish7.png",
            "img/fish/fish8.png",
            "img/fish/fish9.png",
            "img/fish/fish10.png",
            "img/fish/shark1.png",
            "img/fish/shark2.png"
        ],
        [


        ],
        "img/Interface/b.jpg",
        []
    ],
    [
        [
            "img/fish/fish1.png",
            "img/fish/fish2.png",
            "img/fish/fish3.png",
            "img/fish/fish4.png",
            "img/fish/fish5.png",
            "img/fish/fish6.png",
            "img/fish/fish7.png",
            "img/fish/fish8.png",
            "img/fish/fish9.png",
            "img/fish/fish10.png",
            "img/fish/shark1.png",
            "img/fish/shark2.png",
            "img/fish/fish12.png"
        ],
        [


        ],
        "img/Interface/c.jpg",
        []
    ],
    [
        [
            "img/fish/fish1.png",
            "img/fish/fish2.png",
            "img/fish/fish3.png",
            "img/fish/fish4.png",
            "img/fish/fish5.png",
            "img/fish/fish6.png",
            "img/fish/fish7.png",
            "img/fish/fish8.png",
            "img/fish/fish9.png",
            "img/fish/fish10.png",
            "img/fish/fish11.png",
            "img/fish/fish12.png",
            "img/fish/shark1.png",
            "img/fish/shark2.png",
            "img/fish/fish12.png"
        ],
        [


        ],
        "img/Interface/d.jpg",
        []
    ]
];
(function(){
    /*创建1x8的鱼*/
    function addFish1(arr,Obj){
        var defaultObj={
            addNum:1,
            imgUrl:"img/fish/fish1.png",
            maxNum:10,//创建鱼的最大数量
            w:55,
            h:37,
            createTimeBuf:1500,
            addTime:0,
            PH:1,
            moveSpeed:5,
            deathNum:0.4,
            createTime:-10,
            imgInfoAg:"1x8",
            imgInfoAg02:"0"
        };
        extend(defaultObj,Obj);
        arr.push({
            imgUrl:defaultObj.imgUrl,
            w:defaultObj.w,
            h:defaultObj.h,
            moveSpeed:defaultObj.moveSpeed,
            imgInfoAg:defaultObj.imgInfoAg,
            imgInfoAg02:defaultObj.imgInfoAg02,
            addNum:defaultObj.addNum,
            maxNum:defaultObj.maxNum,//创建鱼的最大数量
            defaultAngle:-1,//默认的面向角度
            fishType:"ySmall",
            fishXInfo:[-50,1024],
            fishYInfo:[-defaultObj.w-37,-defaultObj.w],
            minAngleInfo:[0,45],
            maxAngleInfo:[135,180],
            PH:defaultObj.PH,
            deathNum:defaultObj.deathNum,
            createTime:defaultObj.createTime,
            createTimeBuf:defaultObj.createTimeBuf+defaultObj.addTime,
            method:getArrObj.getFishInfo(),
            method02:getArrObj.getFishInfo02()
        });
        arr.push({
            imgUrl:defaultObj.imgUrl,
            w:defaultObj.w,
            h:defaultObj.h,
            moveSpeed:defaultObj.moveSpeed,
            PH:defaultObj.PH,
            deathNum:defaultObj.deathNum,

            addNum:defaultObj.addNum,
            imgInfoAg:defaultObj.imgInfoAg,
            imgInfoAg02:defaultObj.imgInfoAg02,
            maxNum:defaultObj.maxNum,//创建鱼的最大数量
            defaultAngle:-1,//默认的面向角度
            fishType:"ySmall",
            fishXInfo:[-50,1024],
            fishYInfo:[768+defaultObj.w,768+defaultObj.w+50],
            minAngleInfo:[180,225],
            maxAngleInfo:[315,360],
            createTime:defaultObj.createTime,
            createTimeBuf:defaultObj.createTimeBuf+defaultObj.addTime*2,
            method:getArrObj.getFishInfo(),
            method02:getArrObj.getFishInfo02()
        });
        arr.push({
            imgUrl:defaultObj.imgUrl,
            w:defaultObj.w,
            h:defaultObj.h,
            imgInfoAg:defaultObj.imgInfoAg,
            imgInfoAg02:defaultObj.imgInfoAg02,
            moveSpeed:defaultObj.moveSpeed,
            addNum:defaultObj.addNum,
            maxNum:parseInt(defaultObj.maxNum/2),//创建鱼的最大数量
            defaultAngle:-1,//默认的面向角度
            fishType:"ySmall",
            fishXInfo:[-defaultObj.w-30,-defaultObj.w],
            fishYInfo:[-50,800],
            minAngleInfo:[270,300],
            maxAngleInfo:[330,360],
            PH:defaultObj.PH,
            deathNum:defaultObj.deathNum,
            createTime:defaultObj.createTime,
            createTimeBuf:defaultObj.createTimeBuf+defaultObj.addTime*3,
            method:getArrObj.getFishInfo(),
            method02:getArrObj.getFishInfo02()
        });
        arr.push( {
            imgUrl:defaultObj.imgUrl,
            w:defaultObj.w,
            moveSpeed:defaultObj.moveSpeed,
            h:defaultObj.h,
            imgInfoAg:defaultObj.imgInfoAg,
            imgInfoAg02:defaultObj.imgInfoAg02,
            addNum:defaultObj.addNum,
            maxNum:parseInt(defaultObj.maxNum/2),//创建鱼的最大数量
            defaultAngle:-1,//默认的面向角度
            fishType:"ySmall",
            fishXInfo:[-defaultObj.w-34,-defaultObj.w],
            fishYInfo:[-50,800],
            minAngleInfo:[0,30],
            maxAngleInfo:[75,90],
            PH:defaultObj.PH,
            deathNum:defaultObj.deathNum,
            createTime:defaultObj.createTime,
            createTimeBuf:defaultObj.createTimeBuf+defaultObj.addTime*4,
            method:getArrObj.getFishInfo(),
            method02:getArrObj.getFishInfo02()
        });
        arr.push({
            imgUrl:defaultObj.imgUrl,
            w:defaultObj.w,
            h:defaultObj.h,
            imgInfoAg:defaultObj.imgInfoAg,
            imgInfoAg02:defaultObj.imgInfoAg02,
            deathNum:defaultObj.deathNum,
            addNum:defaultObj.addNum,
            moveSpeed:defaultObj.moveSpeed,
            maxNum:defaultObj.maxNum,//创建鱼的最大数量
            defaultAngle:-1,//默认的面向角度
            fishType:"ySmall",
            fishXInfo:[1024+defaultObj.w,1024+defaultObj.w+30],
            fishYInfo:[-50,800],
            minAngleInfo:[90,135],
            maxAngleInfo:[225,270],
            PH:defaultObj.PH,
            createTime:defaultObj.createTime,
            createTimeBuf:defaultObj.createTimeBuf+defaultObj.addTime*5,
            method:getArrObj.getFishInfo(),
            method02:getArrObj.getFishInfo02()
        });
    }
    /*创建鱼2*/
    function addFish2(arr){
        arr.push({
            imgUrl:"img/fish/fish2.png",
            w:78,
            h:64,
            imgInfoAg:"1x8",
            imgInfoAg02:"0",
            addNum:15,
            maxNum:10,//创建鱼的最大数量
            defaultAngle:-1,//默认的面向角度
            fishType:"ySmall",
            fishXInfo:[-100,1024],
            fishYInfo:[-100,-64],
            minAngleInfo:[0,90],
            maxAngleInfo:[90,180],
            createTime:-10,
            deathNum:0.35,
            createTimeBuf:1500,
            method:getArrObj.getFishInfo(),
            method02:getArrObj.getFishInfo02()
        });
        arr.push({
            imgUrl:"img/fish/fish2.png",
            w:78,
            h:64,
            imgInfoAg:"1x8",
            imgInfoAg02:"0",
            addNum:15,
            maxNum:10,//创建鱼的最大数量
            defaultAngle:-1,//默认的面向角度
            fishType:"ySmall",
            fishXInfo:[-100,1024],
            fishYInfo:[750,800],
            minAngleInfo:[180,270],
            maxAngleInfo:[270,360],
            createTime:-10,
            deathNum:0.35,
            createTimeBuf:1500,
            method:getArrObj.getFishInfo(),
            method02:getArrObj.getFishInfo02()
        });
    }

    for(var i =0;i<cjData.length;i++){
        addFish1(cjData[i][1]);
        addFish1(cjData[i][1],{
            addNum:10,
            imgUrl:"img/fish/fish3.png",
            maxNum:5,//创建鱼的最大数量
            w:72,
            h:56,
            createTimeBuf:4000,
            PH:1,
            addTime:200,
            deathNum:0.3,
            createTime:3000
        });
        addFish1(cjData[i][1],{
            addNum:20,
            imgUrl:"img/fish/fish4.png",
            maxNum:5,//创建鱼的最大数量
            w:77,
            h:59,
            addTime:200,
            moveSpeed:4.5,
            createTimeBuf:6000,
            PH:1,
            deathNum:0.25,
            createTime:3000
        });
        addFish1(cjData[i][1],{
            addNum:16,
            imgUrl:"img/fish/fish5.png",
            maxNum:5,//创建鱼的最大数量
            w:107,
            h:122,
            addTime:1000,
            moveSpeed:4,
            createTimeBuf:6000,
            PH:1,
            deathNum:0.33,
            createTime:1000
        });
        addFish1(cjData[i][1],{
            addNum:30,
            imgUrl:"img/fish/fish6.png",
            maxNum:5,//创建鱼的最大数量
            w:105,
            h:79,
            imgInfoAg:"1x12",
            imgInfoAg02:"2",
            addTime:1000,
            moveSpeed:4,
            createTimeBuf:6000,
            PH:2,
            deathNum:0.20,
            createTime:1000
        });
        addFish1(cjData[i][1],{
            addNum:40,
            imgUrl:"img/fish/fish7.png",
            maxNum:5,//创建鱼的最大数量
            w:92,
            h:151,
            imgInfoAg:"1x10",
            imgInfoAg02:"3",
            addTime:3000,
            moveSpeed:4,
            createTimeBuf:12000,
            PH:4,
            deathNum:0.15,
            createTime:3000
        });
        addFish1(cjData[i][1],{
            addNum:50,
            imgUrl:"img/fish/fish8.png",
            maxNum:5,//创建鱼的最大数量
            w:174,
            h:126,
            imgInfoAg:"1x12",
            imgInfoAg02:"2",
            addTime:3000,
            moveSpeed:3,
            createTimeBuf:24000,
            PH:5,
            deathNum:0.10,
            createTime:6000
        });
        if(i>=1){
            addFish1(cjData[i][1],{
                addNum:60,
                imgUrl:"img/fish/fish9.png",
                maxNum:1,//创建鱼的最大数量
                w:166,
                h:183,
                imgInfoAg:"1x12",
                imgInfoAg02:"2",
                addTime:3000,
                moveSpeed:3,
                createTimeBuf:24000,
                PH:6,
                deathNum:0.05,
                createTime:8000
            });
        }
        if(i>=2){
            addFish1(cjData[i][1],{
                addNum:80,
                imgUrl:"img/fish/fish10.png",
                maxNum:1,//创建鱼的最大数量
                w:178,
                h:187,
                imgInfoAg:"1x10",
                imgInfoAg02:"3",
                addTime:3000,
                moveSpeed:3,
                createTimeBuf:24000,
                PH:8,
                deathNum:0.04,
                createTime:8000
            });
        }
        if(i>=3){
            addFish1(cjData[i][1],{
                addNum:100,
                w:509,
                h:270,
                moveSpeed:5,
                PH:8,
                deathNum:0.02,
                imgUrl:"img/fish/shark1.png",
                maxNum:1,//创建鱼的最大数量
                imgInfoAg:"1x12",
                imgInfoAg02:"2",
                addTime:3000,
                createTimeBuf:24000,
                createTime:8000
            });
        }
        if(i>=4){
            addFish1(cjData[i][1],{
                addNum:120,
                w:516,
                h:273,
                moveSpeed:3,
                PH:10,
                deathNum:0.02,
                imgUrl:"img/fish/shark2.png",
                maxNum:1,//创建鱼的最大数量
                imgInfoAg:"1x12",
                imgInfoAg02:"2",
                addTime:3000,
                createTimeBuf:36000,
                createTime:18000
            });
        }
        if(i>=5){
            addFish1(cjData[i][1],{
                addNum:140,
                w:215,
                h:211,
                moveSpeed:3,
                PH:12,
                deathNum:0.015,
                imgUrl:"img/fish/fish12.png",
                maxNum:1,//创建鱼的最大数量
                imgInfoAg:"1x15",
                imgInfoAg02:"4",
                addTime:3000,
                createTimeBuf:36000,
                createTime:18000
            });
        }
        if(i>=6){
            addFish1(cjData[i][1],{
                addNum:160,
                w:274,
                h:100,
                moveSpeed:3,
                PH:12,
                deathNum:0.01,
                imgUrl:"img/fish/fish11.png",
                maxNum:1,//创建鱼的最大数量
                imgInfoAg:"1x33",
                imgInfoAg02:"5",
                addTime:3000,
                createTimeBuf:36000,
                createTime:18000
            });
        }
        addFish2(cjData[i][1]);
        addRect3(cjData[i][1],cjData[i][3]);
      //  addRect2(cjData[i][1],cjData[i][3]);
      //  addRect1(cjData[i][1],cjData[i][3]);
    }

    /*增加矩形鱼群1*/
    //num 当前矩形
    //time 持续时间
    function addRect1(arr,arr2){
        arr2.push({
            num:"1",
            time:45
        });
        for(var i =0;i<5;i++){
            arr.push({
                imgUrl:"img/fish/fish1.png",
                w:55,
                h:37,
                imgInfoAg:"1x8",
                imgInfoAg02:"0",
                addNum:1,
                maxNum:100,//创建鱼的最大数量
                defaultAngle:-1,//默认的面向角度
                fishType:"rect1",
                fishXInfo:-55,
                fishYInfo:208.5+37*i+20*i,
                minAngleInfo:0,
                maxAngleInfo:0,
                createTime:0,
                deathNum:0.4,
                createAllTime:5000,
                createAllTimeBuf:5000,
                createTimeBuf:300,
                method:getArrObj.getFishInfo(),
                method02:getArrObj.getFishInfo02(),
                createFishEnd:function(fish){
                    fish.isChangeAngle=false;
                }
            });
            arr.push({
                imgUrl:"img/fish/fish3.png",
                w:72,
                h:56,
                imgInfoAg:"1x8",
                imgInfoAg02:"0",
                addNum:10,
                maxNum:100,//创建鱼的最大数量
                defaultAngle:-1,//默认的面向角度
                fishType:"rect1",
                fishXInfo:-72,
                fishYInfo:181+56*i+10*i,
                minAngleInfo:0,
                maxAngleInfo:0,
                createTime:100,
                deathNum:0.35,
                createTimeBufBuf:5000,
                createAllTime:10000,
                createAllTimeBuf:10000,
                createTimeBuf:400,
                method:getArrObj.getFishInfo(),
                method02:getArrObj.getFishInfo02(),
                createFishEnd:function(fish){
                    fish.isChangeAngle=false;
                    fish.method.push({
                        name:"changeAngeleForMoveA"
                    });
                }
            });
            if(i<4){
                arr.push({
                    imgUrl:"img/fish/fish5.png",
                    addNum:16,
                    w:107,
                    h:122,
                    PH:1,
                    deathNum:0.33,
                    imgInfoAg:"1x8",
                    imgInfoAg02:"0",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect1",
                    fishXInfo:-72,
                    fishYInfo:92+122*i+10*i,
                    minAngleInfo:0,
                    maxAngleInfo:0,
                    createTime:100,
                    createTimeBufBuf:10500,
                    createAllTime:15000,
                    createAllTimeBuf:15000,
                    createTimeBuf:400,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                        fish.method.push({
                            name:"changeAngeleForMoveA"
                        });
                    }
                });
            }
            if(i<3){
                arr.push({
                    addNum:60,
                    w:166,
                    h:183,
                    moveSpeed:5,
                    PH:6,
                    deathNum:0.05,
                    imgUrl:"img/fish/fish9.png",
                    imgInfoAg:"1x12",
                    imgInfoAg02:"2",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect1",
                    fishXInfo:-166,
                    fishYInfo:56.5+183*i+10*i,
                    minAngleInfo:0,
                    maxAngleInfo:0,
                    createTime:100,
                    createTimeBufBuf:15500,
                    createAllTime:35000,
                    createAllTimeBuf: 35000,
                    createTimeBuf:1500,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                    }
                });
            }
            if(i<2){
                arr.push({
                    addNum:100,
                    w:509,
                    h:270,
                    moveSpeed:5,
                    PH:8,
                    deathNum:0.02,
                    imgUrl:"img/fish/shark1.png",
                    imgInfoAg:"1x12",
                    imgInfoAg02:"2",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect1",
                    fishXInfo:-509,
                    fishYInfo:66+270*i+10*i,
                    minAngleInfo:0,
                    maxAngleInfo:0,
                    createTime:100,
                    createTimeBufBuf:35500,
                    createAllTime:45000,
                    createAllTimeBuf: 45000,
                    createTimeBuf:2500,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                    }
                });
            }

        }
    }
    function addRect2(arr,arr2){
        arr2.push({
            num:"2",
            time:45
        });
        for(var i =0;i<5;i++){
            arr.push({
                imgUrl:"img/fish/fish1.png",
                w:55,
                h:37,
                imgInfoAg:"1x8",
                imgInfoAg02:"0",
                addNum:1,
                maxNum:100,//创建鱼的最大数量
                defaultAngle:-1,//默认的面向角度
                fishType:"rect2",
                fishXInfo:-55,
                fishYInfo:-37+(+37*i+20*i),
                minAngleInfo:45,
                maxAngleInfo:45,
                createTime:0,
                deathNum:0.4,
                createAllTime:5000,
                createAllTimeBuf:5000,
                createTimeBuf:300,
                method:getArrObj.getFishInfo(),
                method02:getArrObj.getFishInfo02(),
                createFishEnd:function(fish){
                    fish.isChangeAngle=false;
                    fish.method.push({
                        name:"changeAngeleForMoveB"
                    });
                }
            });
            arr.push({
                imgUrl:"img/fish/fish3.png",
                w:72,
                h:56,
                imgInfoAg:"1x8",
                imgInfoAg02:"0",
                addNum:10,
                maxNum:100,//创建鱼的最大数量
                defaultAngle:-1,//默认的面向角度
                fishType:"rect2",
                fishXInfo:-72,
                fishYInfo:-56+(56*i+10*i),
                minAngleInfo:45,
                maxAngleInfo:45,
                createTime:100,
                deathNum:0.35,
                createTimeBufBuf:5000,
                createAllTime:10000,
                createAllTimeBuf:10000,
                createTimeBuf:400,
                method:getArrObj.getFishInfo(),
                method02:getArrObj.getFishInfo02(),
                createFishEnd:function(fish){
                    fish.isChangeAngle=false;
                    fish.method.push({
                        name:"changeAngeleForMoveB"
                    });
                }
            });
            if(i<4){
                arr.push({
                    imgUrl:"img/fish/fish5.png",
                    addNum:16,
                    w:107,
                    h:122,
                    PH:1,
                    deathNum:0.33,
                    imgInfoAg:"1x8",
                    imgInfoAg02:"0",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect2",
                    fishXInfo:-107,
                    fishYInfo:-122+(122*i+10*i),
                    minAngleInfo:45,
                    maxAngleInfo:45,
                    createTime:100,
                    createTimeBufBuf:10500,
                    createAllTime:15000,
                    createAllTimeBuf:15000,
                    createTimeBuf:400,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                        fish.method.push({
                            name:"changeAngeleForMoveB"
                        });
                    }
                });
            }
            if(i<3){
                arr.push({
                    addNum:60,
                    w:166,
                    h:183,
                    moveSpeed:5,
                    PH:6,
                    deathNum:0.05,
                    imgUrl:"img/fish/fish9.png",
                    imgInfoAg:"1x12",
                    imgInfoAg02:"2",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect2",
                    fishXInfo:-166,
                    fishYInfo:-183+(183*i+10*i),
                    minAngleInfo:45,
                    maxAngleInfo:45,
                    createTime:100,
                    createTimeBufBuf:15500,
                    createAllTime:35000,
                    createAllTimeBuf: 35000,
                    createTimeBuf:1500,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                        fish.method.push({
                            name:"changeAngeleForMoveB"
                        });
                    }
                });
            }
            if(i<2){
                arr.push({
                    addNum:100,
                    w:509,
                    h:270,
                    moveSpeed:5,
                    PH:8,
                    deathNum:0.02,
                    imgUrl:"img/fish/shark1.png",
                    imgInfoAg:"1x12",
                    imgInfoAg02:"2",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect2",
                    fishXInfo:-509,
                    fishYInfo:-270-(270*i+10*i),
                    minAngleInfo:45,
                    maxAngleInfo:45,
                    createTime:100,
                    createTimeBufBuf:35500,
                    createAllTime:45000,
                    createAllTimeBuf: 45000,
                    createTimeBuf:2500,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                        fish.method.push({
                            name:"changeAngeleForMoveB"
                        });
                    }
                });
            }

        }
    }
    function addRect3(arr,arr2){
        arr2.push({
            num:"3",
            time:45
        });
        for(var i =0;i<5;i++){
            arr.push({
                imgUrl:"img/fish/fish1.png",
                w:55,
                h:37,
                imgInfoAg:"1x8",
                imgInfoAg02:"0",
                addNum:1,
                maxNum:100,//创建鱼的最大数量
                defaultAngle:-1,//默认的面向角度
                fishType:"rect3",
                fishXInfo:-55,
                fishYInfo:37*i+20*i,
                minAngleInfo:0,
                maxAngleInfo:0,
                createTime:0,
                deathNum:0.4,
                createAllTime:5000,
                createAllTimeBuf:5000,
                createTimeBuf:300,
                method:getArrObj.getFishInfo(),
                method02:getArrObj.getFishInfo02(),
                createFishEnd:function(fish){
                    fish.isChangeAngle=false;
                    fish.method.push({
                        name:"changeAngeleForMoveC"
                    });
                }
            });
            arr.push({
                imgUrl:"img/fish/fish3.png",
                w:72,
                h:56,
                imgInfoAg:"1x8",
                imgInfoAg02:"0",
                addNum:10,
                maxNum:100,//创建鱼的最大数量
                defaultAngle:-1,//默认的面向角度
                fishType:"rect3",
                fishXInfo:-72,
                fishYInfo:56*i+10*i,
                minAngleInfo:0,
                maxAngleInfo:0,
                createTime:100,
                deathNum:0.35,
                createTimeBufBuf:5000,
                createAllTime:10000,
                createAllTimeBuf:10000,
                createTimeBuf:400,
                method:getArrObj.getFishInfo(),
                method02:getArrObj.getFishInfo02(),
                createFishEnd:function(fish){
                    fish.isChangeAngle=false;
                    fish.method.push({
                        name:"changeAngeleForMoveC"
                    });
                }
            });
            if(i<4){
                arr.push({
                    imgUrl:"img/fish/fish5.png",
                    addNum:16,
                    w:107,
                    h:122,
                    PH:1,
                    deathNum:0.33,
                    imgInfoAg:"1x8",
                    imgInfoAg02:"0",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect3",
                    fishXInfo:-107,
                    fishYInfo:122*i+10*i,
                    minAngleInfo:0,
                    maxAngleInfo:0,
                    createTime:100,
                    createTimeBufBuf:10500,
                    createAllTime:15000,
                    createAllTimeBuf:15000,
                    createTimeBuf:400,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                        fish.method.push({
                            name:"changeAngeleForMoveC"
                        });
                    }
                });
            }
            if(i<3){
                arr.push({
                    addNum:60,
                    w:166,
                    h:183,
                    moveSpeed:5,
                    PH:6,
                    deathNum:0.05,
                    imgUrl:"img/fish/fish9.png",
                    imgInfoAg:"1x12",
                    imgInfoAg02:"2",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect3",
                    fishXInfo:-166,
                    fishYInfo:183*i+10*i,
                    minAngleInfo:0,
                    maxAngleInfo:0,
                    createTime:100,
                    createTimeBufBuf:35500,
                    createAllTime:45000,
                    createAllTimeBuf: 45000,
                    createTimeBuf:1200,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                        fish.method.push({
                            name:"changeAngeleForMoveC"
                        });
                    }
                });
                arr.push({
                    addNum:50,
                    w:174,
                    h:126,
                    imgInfoAg:"1x12",
                    imgInfoAg02:"2",
                    moveSpeed:5,
                    PH:5,
                    deathNum:0.10,
                    imgUrl:"img/fish/fish8.png",
                    maxNum:100,//创建鱼的最大数量
                    defaultAngle:-1,//默认的面向角度
                    fishType:"rect3",
                    fishXInfo:-166,
                    fishYInfo:183*i+10*i,
                    minAngleInfo:0,
                    maxAngleInfo:0,
                    createTime:100,
                    createTimeBufBuf:15500,
                    createAllTime:35000,
                    createAllTimeBuf: 35000,
                    createTimeBuf:1300,
                    method:getArrObj.getFishInfo(),
                    method02:getArrObj.getFishInfo02(),
                    createFishEnd:function(fish){
                        fish.isChangeAngle=false;
                        fish.method.push({
                            name:"changeAngeleForMoveC"
                        });
                    }
                });
            }
        }
    }
})();